import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
const browser=await chromium.launch({headless:true})
try {
  const page=await browser.newPage({viewport:{width:1200,height:1000}})
  const errors=[];page.on('pageerror',()=>errors.push('browser exception'))
  await page.goto('http://127.0.0.1:13087/manage/')
  await page.getByText('添加服务器',{exact:true}).click()
  await page.locator('#create input[name=id]').fill('browser-test')
  await page.locator('#create input[name=server]').fill('edge.example.com')
  await page.locator('#create input[name=tlsServerName]').fill('edge.example.com')
  await page.locator('#create input[name=realityServerName]').fill('www.example.org')
  await page.locator('#create button').click()
  await page.locator('#version').filter({hasText:'v1'}).waitFor()
  await page.locator('#protocol-vless').uncheck()
  await page.locator('#protocol-hysteria2').uncheck()
  await page.locator('#port-anytls').fill('9443')
  await page.locator('#port-tuic').fill('9443')
  await page.locator('#users').fill('default\nalice')
  await page.getByRole('button',{name:'保存草稿',exact:true}).click()
  await page.locator('#draftState').filter({hasText:'已有未发布草稿'}).waitFor()
  assert.equal(await page.locator('#version').textContent(),'v1')
  await page.reload()
  await page.getByRole('button',{name:'browser-test · 离线',exact:true}).click()
  await page.locator('#draftState').filter({hasText:'已有未发布草稿'}).waitFor()
  assert.equal(await page.locator('#port-anytls').inputValue(),'9443')
  await page.getByRole('button',{name:'发布草稿',exact:true}).click()
  await page.locator('#version').filter({hasText:'v2'}).waitFor()
  await page.locator('#downloadUser').selectOption('alice')
  assert.ok((await page.locator('#macos').getAttribute('href')).endsWith('/v1/config/client/browser-test/macos?user=alice'))
  await page.locator('#versions').selectOption('1')
  await page.getByRole('button',{name:'回滚为所选版本',exact:true}).click()
  await page.locator('#version').filter({hasText:'v3'}).waitFor()
  assert.equal(await page.locator('#protocol-vless').isChecked(),true)
  assert.equal(await page.locator('#port-anytls').inputValue(),'443')
  await page.getByRole('button',{name:'生成一次性接入码',exact:true}).click()
  await page.locator('#enrollment').waitFor({state:'visible'})
  assert.equal((await page.locator('#code').textContent()).length,43)
  assert.ok((await page.locator('#install').textContent()).includes('--id browser-test'))
  page.once('dialog',dialog=>dialog.accept())
  await page.getByRole('button',{name:'撤销机器授权',exact:true}).click()
  await page.locator('#enrollment').waitFor({state:'hidden'})
  await page.setViewportSize({width:390,height:844})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  assert.deepEqual(errors,[])
  console.log('Browser create, draft persistence, publication, rollback, user downloads, enrollment, revocation and mobile layout PASS')
} catch {
  console.error('Browser smoke failed; credentials and page contents suppressed.')
  process.exitCode=1
} finally {await browser.close()}
