import { chromium } from '@playwright/test'
import assert from 'node:assert/strict'
const browser=await chromium.launch({headless:true})
try {
  const page=await browser.newPage({viewport:{width:1200,height:1000}})
  page.setDefaultTimeout(15000)
  const errors=[];page.on('pageerror',()=>errors.push('browser exception'))
  await page.goto('http://127.0.0.1:13087/manage/')
  await page.getByText('添加机器',{exact:true}).first().click()
  await page.locator('#create input[name=id]').fill('browser-test')
  await page.locator('#create button').click()
  await page.locator('#version').filter({hasText:'v1'}).waitFor()
  assert.equal(await page.locator('#enabled').isChecked(),false)
  assert.equal(await page.locator('#server').inputValue(),'')
  assert.equal(await page.locator('#editTLS').isVisible(),false)
  assert.equal(await page.locator('#editReality').isVisible(),false)
  await page.getByRole('button',{name:'生成一次性接入码',exact:true}).click()
  await page.locator('#enrollment').waitFor({state:'visible'})
  assert.equal((await page.locator('#code').textContent()).length,43)
  assert.ok((await page.locator('#install').textContent()).includes('/v1/agent/browser-test/compose.yaml'))
  console.log('Browser machine-only creation and enrollment before proxy configuration PASS')
  await page.locator('#protocol-anytls').check()
  await page.locator('#protocol-tuic').check()
  await page.locator('#port-anytls').fill('9443')
  await page.locator('#port-tuic').fill('9443')
  await page.locator('#server').fill('edge.example.com')
  await page.locator('#tls').fill('edge.example.com')
  await page.locator('#enabled').check()
  assert.ok((await page.locator('#requiredPorts').textContent()).includes('TCP 80'))
  assert.ok((await page.locator('#requiredPorts').textContent()).includes('UDP 9443'))
  await page.locator('#users').fill('default\nalice')
  await page.getByRole('button',{name:'保存草稿',exact:true}).click()
  await page.locator('#draftState').filter({hasText:'已有未发布草稿'}).waitFor()
  assert.equal(await page.locator('#version').textContent(),'v1')
  await page.reload()
  await page.getByRole('button',{name:'browser-test · 离线',exact:true}).click()
  await page.locator('#draftState').filter({hasText:'已有未发布草稿'}).waitFor()
  assert.equal(await page.locator('#port-anytls').inputValue(),'9443')
  await page.getByRole('button',{name:'发布草稿',exact:true}).click()
  await page.locator('#version').filter({hasText:'v2'}).waitFor()
  await page.locator('#downloadUser').selectOption('alice')
  assert.ok((await page.locator('#macos').getAttribute('href')).endsWith('/v1/config/client/browser-test/macos?user=alice'))
  await page.locator('#credentialUser').selectOption('alice')
  page.once('dialog',dialog=>dialog.accept())
  await page.getByRole('button',{name:'生成新凭据并发布',exact:true}).click()
  await page.locator('#version').filter({hasText:'v3'}).waitFor()
  await page.locator('#versions').selectOption('1')
  await page.getByRole('button',{name:'回滚为所选版本',exact:true}).click()
  await page.locator('#version').filter({hasText:'v4'}).waitFor()
  assert.equal(await page.locator('#protocol-vless').isChecked(),false)
  assert.equal(await page.locator('#enabled').isChecked(),false)
  page.once('dialog',dialog=>dialog.accept())
  await page.getByRole('button',{name:'撤销机器授权',exact:true}).click()
  await page.locator('#enrollment').waitFor({state:'hidden'})
  await page.getByText('添加机器',{exact:true}).first().click()
  await page.locator('#create input[name=id]').fill('browser-reality-only')
  await page.locator('#create button').click()
  await page.locator('#name').filter({hasText:'browser-reality-only'}).waitFor()
  await page.locator('#protocol-vless').check()
  assert.equal(await page.locator('#editTLS').isVisible(),false)
  assert.equal(await page.locator('#editReality').isVisible(),true)
  await page.locator('#server').fill('192.0.2.1')
  await page.locator('#reality').fill('www.example.org')
  await page.locator('#enabled').check()
  assert.equal((await page.locator('#requiredPorts').textContent()).includes('TCP 80'),false)
  await page.getByRole('button',{name:'保存草稿',exact:true}).click()
  await page.locator('#draftState').filter({hasText:'已有未发布草稿'}).waitFor()
  await page.getByRole('button',{name:'发布草稿',exact:true}).click()
  await page.locator('#version').filter({hasText:'v2'}).waitFor()
  await page.setViewportSize({width:390,height:844})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  assert.deepEqual(errors,[])
  console.log('Browser later protocol/port configuration, drafts, publication, user credentials, rollback and mobile layout PASS')
} catch {
  console.error('Browser smoke failed; credentials and page contents suppressed.')
  process.exitCode=1
} finally {await browser.close()}
