const $ = id => document.getElementById(id)
const base = new URL('../',location.href)
let selected, current, defaults, pending = false, enrollmentTimer
const types = ['anytls','vless','tuic','hysteria2']
const names = { anytls:'AnyTLS · TCP',vless:'VLESS Reality · TCP',tuic:'TUIC · UDP',hysteria2:'Hysteria2 · UDP' }
const statusNames = {applied:'已应用',stopped:'已停止',failed_validation:'配置校验失败',failed_start:'启动失败，已尝试恢复',failed_rollback:'恢复失败，请检查机器'}
function message(text,error=false){$('message').textContent=text;$('message').className=error?'error':''}
async function api(path,method='GET',body){const response=await fetch(new URL(path,base),{method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});if(!response.ok)throw new Error(response.status===409?'配置已被其他操作更新，请刷新后编辑。':response.status===401||response.status===403?'当前连接无权访问，请通过你的内网打开管理页面。':'操作失败（HTTP '+response.status+'）');return response.json()}
async function action(fn){if(pending)return;pending=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){message(e.message,true)}finally{pending=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);$('publish').disabled=!current?.draft}}
function clearEnrollment(){clearTimeout(enrollmentTimer);$('enrollment').hidden=true;$('code').textContent=''}
function online(seen){return seen&&Date.now()-new Date(seen).getTime()<90000}
async function list(){const result=await api('v1/machines');defaults=result.defaultPolicy;const container=$('machines');container.replaceChildren();for(const m of result.machines){const b=document.createElement('button');b.textContent=m.id+' · '+(online(m.last_seen)?'在线':'离线');b.className=m.id===selected?'selected':'';b.onclick=()=>action(async()=>{selected=m.id;clearEnrollment();await load();await list()});container.append(b)}if(!result.machines.length)container.textContent='还没有代理服务器'}
function downloads(){for(const platform of ['linux','macos'])$(platform).href=new URL('v1/config/client/'+selected+'/'+platform+'?user='+encodeURIComponent($('downloadUser').value),base).href}
async function load(){if(!selected)return;current=await api('v1/machines/'+selected);$('empty').hidden=true;$('detail').hidden=false;$('name').textContent=selected;$('online').textContent=online(current.lastSeen)?'在线':'离线';$('version').textContent='v'+current.version;$('reported').textContent=current.reportedVersion?'v'+current.reportedVersion:'尚未上报';$('status').textContent=statusNames[current.reportedStatus]||'等待接入';$('seen').textContent=current.lastSeen?'最近连接：'+new Date(current.lastSeen).toLocaleString():'机器尚未连接配置中心';const draft=current.draft;const spec=draft?.spec||current.spec;const p=draft?.policy||current.policy;for(const [id,key] of [['server','server'],['tls','tlsServerName'],['reality','realityServerName'],['email','acmeEmail']])$(id).value=spec[key]||'';$('enabled').checked=p.enabled;$('logLevel').value=p.logLevel;$('users').value=p.users.join('\n');$('dns').value=p.dns?JSON.stringify(p.dns,null,2):'';$('route').value=p.route?JSON.stringify(p.route,null,2):'';const fields=$('protocols');fields.replaceChildren();for(const t of types){const group=document.createElement('div');const label=document.createElement('label');label.className='inline';const checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.id='protocol-'+t;checkbox.checked=p.protocols.includes(t);label.append(checkbox,document.createTextNode(names[t]));const port=document.createElement('input');port.type='number';port.min=1;port.max=65535;port.id='port-'+t;port.value=p.ports[t];port.setAttribute('aria-label',names[t]+' 端口');group.append(label,port);fields.append(group)}$('draftState').textContent=draft?(draft.base_version===current.version?'已有未发布草稿':'草稿已过期，请重新保存'):'没有未发布修改';$('publish').disabled=!draft;$('versions').replaceChildren();for(const v of current.versions){const option=document.createElement('option');option.value=v.version;option.textContent='v'+v.version+' · '+new Date(v.created_at).toLocaleString();$('versions').append(option)}$('enrolled').textContent=current.enrolled?'已分配机器凭据；重新接入会替换旧凭据。':'尚未分配机器凭据。';$('downloadUser').replaceChildren();for(const user of current.policy.users){const o=document.createElement('option');o.value=o.textContent=user;$('downloadUser').append(o)}downloads()}
$('create').onsubmit=e=>{e.preventDefault();action(async()=>{const values=Object.fromEntries(new FormData(e.target));selected=values.id;delete values.id;await api('v1/machines/'+selected,'PUT',values);e.target.reset();clearEnrollment();await list();await load();message('服务器已添加。生成接入码后，在机器上安装同步程序。')})}
$('edit').onsubmit=e=>{e.preventDefault();action(async()=>{const policy={enabled:$('enabled').checked,protocols:types.filter(t=>$('protocol-'+t).checked),ports:Object.fromEntries(types.map(t=>[t,Number($('port-'+t).value)])),users:$('users').value.split(/\s+/).filter(Boolean),logLevel:$('logLevel').value};for(const section of ['dns','route'])if($(section).value.trim())policy[section]=JSON.parse($(section).value);const spec={server:$('server').value,tlsServerName:$('tls').value,realityServerName:$('reality').value};if($('email').value)spec.acmeEmail=$('email').value;await api('v1/machines/'+selected+'/draft','PUT',{baseVersion:current.version,spec,policy});await load();message('草稿已保存，发布后机器才会拉取更新。')})}
$('publish').onclick=()=>action(async()=>{await api('v1/machines/'+selected+'/publish','POST',{baseVersion:current.version});await load();await list();message('已发布，等待机器拉取并上报应用结果。')})
$('rollback').onclick=()=>action(async()=>{await api('v1/machines/'+selected+'/rollback','POST',{baseVersion:current.version,version:Number($('versions').value)});await load();message('回滚已发布，等待机器应用。')})
$('enroll').onclick=()=>action(async()=>{clearEnrollment();const result=await api('v1/machines/'+selected+'/enrollment','POST',{});$('code').textContent=result.code;$('install').textContent='sudo curl -fsS https://api.nokiy.net/sing-box/v1/agent/bootstrap.py -o /usr/local/lib/sing-box-bootstrap.py\nsudo python3 /usr/local/lib/sing-box-bootstrap.py install --url https://api.nokiy.net/sing-box --id '+selected;$('enrollment').hidden=false;enrollmentTimer=setTimeout(clearEnrollment,result.expiresIn*1000);message('接入码已生成。')})
$('revoke').onclick=()=>action(async()=>{if(!confirm('撤销后，这台机器无法继续下载配置或上报状态。已有代理进程会继续运行。'))return;await api('v1/machines/'+selected+'/revoke','POST',{});clearEnrollment();await load();message('机器授权已撤销。')})
$('copy').onclick=()=>action(async()=>{await navigator.clipboard.writeText($('code').textContent);message('已复制接入码。')})
$('downloadUser').onchange=downloads
$('refresh').onclick=()=>action(async()=>{await list();await load();message('状态已刷新。')})
setInterval(()=>{if(selected&&!pending)api('v1/machines/'+selected).then(m=>{$('online').textContent=online(m.lastSeen)?'在线':'离线';$('reported').textContent=m.reportedVersion?'v'+m.reportedVersion:'尚未上报';$('status').textContent=statusNames[m.reportedStatus]||'等待接入';$('seen').textContent=m.lastSeen?'最近连接：'+new Date(m.lastSeen).toLocaleString():'机器尚未连接配置中心'}).catch(()=>{})},30000)
action(list)
